# 1.Artificial Intelligence

## Iris 데이타셋 예시

In [2]:
from sklearn import datasets
iris_bunch = datasets.load_iris()

In [3]:
print(type(iris_bunch))

<class 'sklearn.utils.Bunch'>


In [4]:
iris_bunch.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
iris_bunch.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [7]:
iris_bunch.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
iris_bunch.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
iris_bunch.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
iris_bunch.data.shape

(150, 4)

In [11]:
iris_bunch.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
iris_bunch.target.shape

(150,)

## 데이타 분할 예제

In [13]:
import numpy as np
import sklearn.model_selection as model_selection

X = np.arange(10)
y = X * X
print(X, y)

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, random_state=0, test_size=0.2)
print("X_train", X_train)
print("y_train", y_train)
print("X_test", X_test)
print("y_test", y_test)

[0 1 2 3 4 5 6 7 8 9] [ 0  1  4  9 16 25 36 49 64 81]
X_train [4 9 1 6 7 3 0 5]
y_train [16 81  1 36 49  9  0 25]
X_test [2 8]
y_test [ 4 64]


## 표준화(Standardization)

In [3]:
from sklearn.preprocessing import StandardScaler
import numpy as np

arr = np.array([2,8,10], dtype=np.float32).reshape(-1,1)
print(f'mean: {arr.mean()}, variation: {arr.var()}, std : {arr.std()}')

print((arr-arr.mean())/arr.std())
scaler = StandardScaler()
scaler.fit_transform(arr)

mean: 6.666666507720947, variation: 11.555556297302246, std : 3.399346351623535
[[-1.3728129 ]
 [ 0.39223233]
 [ 0.98058075]]


array([[-1.3728129],
       [ 0.3922323],
       [ 0.9805807]], dtype=float32)

## 정규화(Normalization)

In [36]:
from sklearn.preprocessing import Normalizer
from sklearn.datasets import load_iris
import numpy as np

arr = np.array([[2,8,10]])

l1 = Normalizer('l1')
l1_norm = l1.fit_transform(arr)

l2 = Normalizer('l2')
l2_norm = l2.fit_transform(arr)

lmax = Normalizer('max')
lmax_norm = lmax.fit_transform(arr)

print(l1_norm)
print(l2_norm)
print(lmax_norm)


[[0.1 0.4 0.5]]
[[0.15430335 0.6172134  0.77151675]]
[[0.2 0.8 1. ]]
